# Generated by Django 5.0.1 on 2025-12-05 13:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название знака')),
                ('sign_type', models.CharField(choices=[('stop', 'Стоп'), ('speed_limit', 'Ограничение скорости'), ('no_entry', 'Въезд запрещен'), ('parking', 'Парковка'), ('pedestrian', 'Пешеходный переход'), ('other', 'Другой')], max_length=50, verbose_name='Тип знака')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Дорожный знак',
                'verbose_name_plural': 'Дорожные знаки',
            },
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='detections/%Y/%m/%d/', verbose_name='Изображение')),
                ('confidence', models.FloatField(help_text='Значение от 0 до 1', verbose_name='Уверенность')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='Время детекции')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic_signs.trafficsign', verbose_name='Распознанный знак')),
            ],
            options={
                'verbose_name': 'Результат детекции',
                'verbose_name_plural': 'Результаты детекции',
                'ordering': ['-detected_at'],
            },
        ),
    ]
